version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      SENDGRID_API_KEY: SG.obzJIIcAQSONsAJ6hp5dXg.XBApNpsst-WwLJOaAvGcTzHBw42bANvNpNkOORtiRbU
      MONGODB_URL: mongodb://mongo_db:27017/task-manager-api
      JWT_SECRET: thisismynewcourse
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}